koopjs/FeatureServer

- src/field.js
Feature Server is ignoring the outFields options when generating the fields response.  Therefore, when clients get the response they think the Feature Set response contains these fields, when if fact it may not.  So before creating fields, this fix filters ``` metadata.fields``` so that it will only contain fields contained in the ``` outFields ``` options.
Give this request to Feature Server: (note date, OBJECTID in outfields)
``` FeatureServer/0/query?f=json&geometry={%22xmin%22:-13633964.480821775,%22ymin%22:4540069.018923454,%22xmax%22:-13618753.512193045,%22ymax%22:4553904.1210430525}&geometryType=esriGeometryEnvelope&inSR=102100&spatialRel=esriSpatialRelIntersects&outFields=date,OBJECTID&returnGeometry=true&maxAllowableOffset=38&outSR=102100&resultOffset=0&resultRecordCount=1000&wher …
```
> Fixes #34 - Filter by outfields before creating fields

- src/info.js
if you actually pass multiple layers it breaks when you run a /layers query
> layer info work too

- CHANGELOG.md
- package.json
- src/field/index.js
- src/query.js
- src/templates.js
- templates/layer.json
- test/field.js
- test/info.js
- test/query.js
- test/template.json.js
This new implementation supports using a provider's `idField` from metadata as the source of the OBJECTID field's value.  The field referenced by `idField` is maintained in the `fields` array of both query and layer services.  Support is removed for using a field without name or alias of 'OBJECTID' as the OBJECTID field - which produces buggy behavior in ArcGIS clients.
In addition, log warning are added when an `idField` is not set, or its key/values are potentially problematic in ArcGIS clients.
> Fields array refactor

- CHANGELOG.md
- package.json
- test/query.js
- test/route.js
Bumped winnow to 1.14.0.  Since this winnow includes the switch to creation of integer hashes as OBJECTIDs, FeatureServer tests dependent on OBJECTID values had to be updated.
> Bump winnow and adjust tests.

- CHANGELOG.md
- src/query.js
When `returnGeometry=false` and `outSR=<EPSG>` in same request, query results in winnow return with `attributes: undefined`.  Most likely, this is the result of  not selecting geometry when `returnGeometry=false` (see [here](https://github.com/koopjs/winnow/blob/master/src/select/index.js#L11)) and then an attempting to use missing geometry with the outSR deep inside `alasql` module.
Solution submitted here deletes `outSR` from query params when `returnGeometry=false` is also part of request.
Problem reported here: https://github.com/koopjs/FeatureServer/issues/95
> Problems when returnGeometry=false and outSR=<EPSG> in same request

- .travis.yml
- package.json
- src/field/index.js
- test/info.js
- test/query.js
- test/route.js
- test/template.json.js
Update to standard 12 caused unexpected changes in test results; expected OBJECTIDs changed.  Possibly due to style changes regarding whitespace around object curly braces - this could conceiving change the result of the numeric hashing done to create OBJECTIDs.
> Standard update

- test/route.js
Travis shows a [test failing](https://travis-ci.org/koopjs/FeatureServer/builds/436856410?utm_source=github_status&utm_medium=notification) on latest build despite no recent changes to code base.  I tested the locally and found the same behavior once I deleted `node_modules` and my local `package-lock.json` or a `yarn.lock` file. 
This likely has something to do with an update in a dependency, possibly farmhash, since we use farmhash to create OBJECTIDs, which is what the failing assertion was testing.
> Adjust value for test that was failing on Travis due to update packages.

- CHANGELOG.md
- package.json
- src/route.js
- test/route.js
Add validation to `limit` and `resultRecordCount` parameters.  
Add `resultRecordCount` to the `limit` setting hierarchy.
Bump Winnow.
> Add resultRecordCount to the limit setting hierarchy

- src/info.js
- src/templates.js
- src/utils.js
- templates/layer.json
- test/info.js
- test/template.json.js
This PR includes is a small refactor to simplify the rendering of layer info.
* Moved calculation of `extent` and the `geometryType` lookup into the `renderLayer`, as this pair were always being executed before it and then passed into `renderLayer`
* removed `geometryType` from the `layer.json` template.  This value either comes from provider metadata or is determined by feature data, so no reason to have it in the source template
* removed a series of unnecessary conditional checks in `renderLayer`;  checks were for properties on an object constructed from the `layer.json` template.  We know those properties are there - they are part of the template and under test.  No reason to check.
* refactored the `isTable` and `layersInfo` to make more readable.
> Refactor layer-info

- CHANGELOG.md
- src/query.js
There are a set of checks that warn if feature properties do not match the set of fields specified in the `metadata.fields` array.   These checks had been simply comparing feature property keys to metadata-field names.  But in some cases the feature property keys might be field aliases.  This PR adds a cross check with field alias before logging a warning.
In addition, this PR excludes fields named `OBJECTID` from the check.  That is because `OBJECTID` might be a feature property generated by Winnow, in which case it wouldn't be defined in the `metadata.fields` array.
> Make adjustments to warnings

- CHANGELOG.md
- src/templates.js
- test/route.js
This PR removes `(options.limit >= maxRecordCount)` from the conditional assignment of `json.exceededTransferLimit`.   After some code review, I realized this check was not necessary and can actually break paging behavior of clients.  The check is not necessary because:
1. `option.limit` is already set to `maxRecordCount` when the request doesn't arrive with a `req.query.limit` or a `req.query.resultRecordCount` (see [here](https://github.com/koopjs/FeatureServer/blob/master/src/route.js#L38)).
2. The `option.limit` is already used by the Winnow dependency to determine `limitExceeded` (see [here](https://github.com/koopjs/winnow/blob/master/src/executeQuery.js#L31-L41)). `limitExceeded` is passed back to FeatureServer and used in the check we are aiming to simplify.
3. There is no reason …
> Remove `exceededTransferLimit` check

- package.json
- src/field/index.js
- src/query.js
- src/route.js
Also:
- provider a more descriptive unassigned `idField` warning
- remove details from invalid GeoJSON warning
> Use chalk to colorize warnings

- CHANGELOG.md
- test/query.js
Query requests with param `returnIdsOnly` should return an object with the `objectIdFieldName` property and value.  This PR adds a test to confirm that behavior.
> Add test for objectIdFieldName in query response

- src/route.js
- test/route.js
Applies standard FeatureServer info handler to requests of form `/FeatureServer/info`.
> Support /FeatureServer/info route

- CHANGELOG.md
- src/route.js
- test/route.js
Trailing slashes on  `/FeatureServer/` and `/FeatureServer/:layerId/`  lead to 400 errors; However, ArcGIS Server supports such requests and are equivalent to the same routes without the trailing slash. Some clients use such a call to determine if the resource is a feature service that supports ArcGIS REST API.
The PR adds a regex to properly route such requests.
> Support info routes with trailing slashes

- src/field/index.js
If the object id field was named anything other than OBJECTID it
was not being moved to the start of the response fields (instead
the last field was being moved to the start). Fixed to pick out
the object id based on field type.
> Fix moving object id field to start.

- CHANGELOG.md
- lib/field/index.js
- test/integration/info.spec.js
- test/integration/schemas/index.js
By specifying editable as true in field metadata the resulting feature service will advertise the fields as editable.
> Allow Editable Fields

- lib/server-info-route-handler.js
- test/unit/server-info-route-handler.spec.js
Table id's are currently starting at 0 even if there are layers present. Table ids should start n+1 from last layer id.
> Correctly set table ids when service has layers and tables

- CHANGELOG.md
- lib/query.js
- test/integration/query.spec.js
There is a bug in query.js that prevents queries that have returnCountOnly=true and returnExtent=true from rendering the proper results.  The specific problem lies [here](https://github.com/koopjs/FeatureServer/blob/master/lib/query.js#L33).
```js
if (options.returnCountOnly && data.count !== undefined) return { count: data.count }
```
If `returnCountOnly=true` and `returnExtent=true` (and `data.count` is undefined), FeatureServer returns a response _without_ an extent.
This PR fixes that bug, albeit with quite a lot of refactoring I did to try to make sense of existing logic and flows.
> Refactor query.js and handle returnExtentOnly properly.

- .gitignore
- CHANGELOG.md
- index.js
- lib/server-info-route-handler.js
- test/integration/info.spec.js
- test/integration/schemas/index.js
There was an improperly assigned module in the index.js.  This should not have affected FeatureServer functionality, as router did not use index.js.  Unskipped tests that were failing because of this issue and made a few adjustments.
> Fix server-info layer.

- lib/generateRenderer/createClassificationInfos.js
- lib/generateRenderer/getGeom.js
- lib/query/filter-and-transform.js
- lib/query/index.js
- lib/query/log-warnings.js
- lib/query/render-statistics.js
- test/unit/query/filter-and-transform.spec.js
- test/unit/query/index.spec.js
- test/unit/query/render-statistics.spec.js
This PR makes some minor changes/improvements that were done as part of a bigger effort to refactor the way the `fields` array is generated on layer info and query routes.  The changes here are independent of that refactor, thus separating them out to reduce file count and scope of upcoming PR. Changes include:
- swapping poorly chosen array methods identified by linter; e.g., a `.filter` which really should be a `.forEach`.
- proper handling/wrapping of statistics aggregations from winnow
> Minor changes in advance of bigger refactor PR.

- lib/helpers/fields/constants.js
- lib/helpers/fields/data-type-utils.js
- lib/helpers/fields/esri-type-utils.js
- lib/helpers/fields/field-classes.js
- lib/helpers/fields/fields.js
- lib/helpers/fields/index.js
- lib/helpers/fields/layer-fields.js
- lib/helpers/fields/query-fields.js
- lib/helpers/fields/statistics-fields.js
- test/unit/helpers/fields/constants.spec.js
- test/unit/helpers/fields/data-type-utils.spec.js
- test/unit/helpers/fields/esri-type-utils.spec.js
- test/unit/helpers/fields/field-classes.spec.js
- test/unit/helpers/fields/fields.spec.js
- test/unit/helpers/fields/layer-fields.spec.js
- test/unit/helpers/fields/query-fields.spec.js
- test/unit/helpers/fields/statistics-fields.spec.js
This PR is second in a series that refactors the way FeatureServer generates the `fields` property in the responses for requests to `FeatureServer/:layer/query` and `FeatureServer/:layer/`. 
The `fields` property provides metadata for all of the properties/attributes on each feature.  For example:
https://services2.arcgis.com/zNjnZafDYCAJAbN0/ArcGIS/rest/services/Street_ROW_Trees/FeatureServer/2/query?resultRecordCount=1&outFields=*&where=1%3D1&f=pjson
```json
{
"objectIdFieldName": "OBJECTID",
"uniqueIdField": {
"name": "OBJECTID",
"isSystemMaintained": true
},
"globalIdFieldName": "",
"geometryType": "esriGeometryPoint",
"spatialReference": {
"wkid": 102100,
"latestWkid": 3857
},
"fields": [
{
"name": "OBJECTID",
"type": "esriFieldTypeOID",
"alias": "OBJECTID",
"sqlType": …
```
> New fields generation files and tests.

- CHANGELOG.md
- README.md
- lib/helpers/table-layer-metadata.js
- lib/server-info-route-handler.js
- test/unit/helpers/table-layer-metadata.spec.js
- test/unit/server-info-route-handler.spec.js
This PR allow the service-description and the layer-description to be set at run-time via Express's `app.locals`.
> Set default descriptions via app.locals

- CHANGELOG.md
- lib/helpers/table-layer-metadata.js
- lib/query/render-features.js
- lib/queryRelatedRecords.js
- test/unit/query/render-features.spec.js
This resolves a couple bugs related to how options are normalized in various parts of the library.
The first is explained in #240, but essentially `FeatureLayerMetadata.create` calls `TableLayerMetadata.normalizeInput` with inconsistent options. The normalize call expects the `layerId` to be under `req.params.layer` (this is the case when making a layer request), but when requesting layers metadata from the `/layers` endpoint the layerId is under `req.layerId`.
https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/helpers/table-layer-metadata.js#L27-L32
https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/layers-metadata.js#L10-L12
The `normalizeOptions` call for QueryFields/Fields does not expect a `data` property. …
> Fix inconsistent args with FeatureLayerMetadata.create and QueryFields.create

- CHANGELOG.md
- lib/helpers/table-layer-metadata.js
- test/unit/helpers/table-layer-metadata.spec.js
The `hasZ` setting on the layer-info route is currently hardcoded to `false`, but should be true when data includes Z-coordinates.  This PR allows GeoJSON metadata to override the default.  If the GeoJSON looks like:
```js
{
metadata: {
hasZ: true
}
}
```
then the `hasZ` in the layer-info response will also be true.  So a Koop-provider can set the `geojson.metadata.hasZ` value if it knows the data has Z coordinates, and FeatureServer will respond appropriately.
> Set hasZ from GeoJSON metadata when available
